#!/bin/bash
WATER=$WATER STIR=$STIR; BEST=$(echo "obase=27; $(echo $WATER | tr '[:lower:]' '[:upper:]' | tr -d '.' | tr -cd '[:alnum:]' | tr 'A-Z' '1-9A-Q') + $(echo $STIR | tr '[:lower:]' '[:upper:]' | tr -d '.' | tr -cd '[:alnum:]' | tr 'A-Z' '1-9A-Q')" | bc | tr '0-9A-Q' 'zabcdefghijklmnopqrstuvwxy'); echo $BEST
